# fly.toml app configuration file generated for melipal on 2025-06-26T04:09:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'melipal'
primary_region = 'eze'

[build]

[processes]
app = "python main.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
